### ISSUE TITLE
snakeSV --test_run does not use a correct path

### ISSUE THREAD

**Issue by warthmann** [RajLabMSSM/snakeSV#4]
(snakesv_env) $ cd snakeSV/
(snakesv_env) snakeSV$ ls
config  docs  example  LICENSE  README.md  resources  snakejob  snakeSV  workflow
(snakesv_env) snakeSV$ mkdir snakesv_test
(snakesv_env) snakeSV$ cd snakesv_test
(snakesv_env) snakeSV/snakesv_test$ snakeSV --test_run
Error: Snakefile "/home/norman/miniconda3/envs/snakesv_env/bin//home/norman/miniconda3/envs/snakesv_env/opt/snakeSV/workflow/Snakefile" not found.

**Comment by ricardovialle** [comment]
Hi @warthmann,

Thanks for catching the issue. 
 
A fresh install should fix the problem (`v0.8` build: `py311hdfd78af_1`):
`mamba create -n snakesv_env snakesv`

Cheers,
Ricardo
